[package]
name = "token-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
dotenv = "0.15.0"
futures = "0.3.28"
serde = "1.0.163"
totp-rs = "5.0.2"

[dependencies.mongodb]
version = "2.5.0"