version: '3.1'

services:
  db:
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    image: postgres:alpine
    ports:
      - 5432:5432
  api:
    restart: on-failure
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${DATABASE_NAME}"
    ports:
      - 80:8080